language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - "pip install -e ."
  - "pip install pyflakes"
  - "pip install pep8"

# command to run tests
script:
  - python -c 'from verktyg.testsuite import main; main()';
  - pep8 verktyg setup.py
  - pyflakes verktyg setup.py
